### ISSUE TITLE
Переписать скрипты в один параметризированный скрипт и добавить справку

### ISSUE THREAD

**Issue by carloscondit** [Solbreen/Kaznacheistvo#2]
Предлагаю собрать из всех скриптов один и сделать его параметризированным. То есть все изменяемые значения вынести в параметры скрипта. В частности: каталог для сохранения файлов, прокси и необходимость выгрузки справочника единых казначейских счетов. А также нужна справка к этому скрипту: для чего и как им пользоваться. Это поможет другим людям найти скрипт и понять как его использовать.

**Comment by Solbreen** [comment]
Скрипты "собраны" в один KSDownloader.ps1. Добавлено описание к этому скрипту
