### ISSUE TITLE
Удаление каталога с временными файлами после выгрузки справочника TRSA

### ISSUE THREAD

**Issue by carloscondit** [Solbreen/Kaznacheistvo#3]
В случае если не удастся выгрузить справочник TRSA, папка с временными файлами останется. Переделай конструкцию try/catch так чтобы каталог с временными файлами удалялся независимо от того получится выгрузить справочник TRSA или нет.

**Comment by Solbreen** [comment]
Готово

**Comment by carloscondit** [comment]
Не вижу изменений. Проверь. Попробуй выгрузить справочник TRSA. Открой его в Excel и заново запусти скрипт с выгрузкой TRSA. Будет ошибка при записи в файл. Если ты все исправил, то каталога с временными файлами (архив и xml файл) не должно быть.

**Comment by carloscondit** [comment]
Увидел куда было добавлена команда по удаление каталога для временных файлов. Все верно. Но я имел ввиду другой сценарий. Попробуй сделать тест, который я выше описал. Учти что в этом случае команда по удалению каталога должна быть ОДНА. Возможно придется еще раз прочесть справку к try/catch.

**Comment by Solbreen** [comment]
Сделал. Просто добавил к конструкции finally{}

**Comment by carloscondit** [comment]
Верно. Но добавь в этот же блок finaly сообщение об этом действии в поток Verbose. Соответственно в этом сообщении должно быть видно какой каталог удаляется. Когда будешь закрывать другие запросы, то попробуй найти способ вставлять ссылки на эти изменения. (не факт что получится, но было бы удобно)

**Comment by Solbreen** [comment]
Какие ссылки???
Verbose добавил

**Comment by carloscondit** [comment]
> Какие ссылки??? Verbose добавил

Как-то так: Ты пишешь что внес изменения и даешь ссылку на нужный [коммит](https://github.com/Solbreen/Kaznacheistvo/commit/e10bf9bfe62a50891ea19acff298e4dc3b629d9c).
